// Product Action
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS";

// Customer Action
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const RETRIEVE_CUSTOMERS = 'RETRIEVE_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_ALL_CUSTOMERS = 'DELETE_ALL_CUSTOMERS';
export const FIND_CUSTOMERS_BY_NAME = 'FIND_CUSTOMERS_BY_NAME';

// Category Action 
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const RETRIEVE_CATEGORYS = 'RETRIEVE_CATEGORYS';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_ALL_CATEGORYS = 'DELETE_ALL_CATEGORYS';
export const FIND_CATEGORYS_BY_NAME = 'FIND_CATEGORYS_BY_NAME';


// Order Action
export const CREATE_ORDER = "CREATE_ORDER";
export const RETRIEVE_ORDERS = "RETRIEVE_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ALL_ORDERS = "DELETE_ALL_ORDERS";